/*	Name: Chris Boyd
*	Date: March 4,2017
*	
*	Description:
*	Implement Kruskal’s minimum spanning tree algorithm.
*	Reads edges from a text file and generates the minimum
*	spanning tree and prints out the edges.
*/
#include "KruskalsMST.h"
#include <iostream>
using namespace std;

int main()
{
	{
		cout << "Proof using Class Example\n\n";
		KruskalsMST mst("input.txt");
		cout << "Initialized Kruskals AVL Tree With VertexNode Linked List\n\n";
		mst.print();
		mst.search();
		cout << "\nSearched Kruskals AVL Tree With VertexNode Linked List\n\n";
		mst.print();
		cout << "\nEdges of Kruskal's MST\n\n";
		mst.tree();
	}
	{
		cout << "\nOutput generated by graph.txt\n\n";
		KruskalsMST mst("graph.txt");
		cout << "\nInitialized Kruskals AVL Tree With VertexNode Linked List\n\n";
		mst.print();
		mst.search();
		cout << "\nSearched Kruskals AVL Tree With VertexNode Linked List\n\n";
		mst.print();
		cout << "\nEdges of Kruskal's MST\n\n";
		mst.tree();
	}
	return 0;
}